### PR TITLE
Python 3.x version

### PR DESCRIPTION
**Pull request by JOEWONGLVFS**
I've changed the code a little so as to make it suitable for Python 3.x. I don't know if it has any errors but it seems to work well on my machine...

### CODE REVIEW

**Comment by hermanschaaf** [comment]
Thanks for the PR @JOEWONGLVFS, this is something a lot of people have been requesting. I haven't been maintaining this library for a while now, but I see more test cases are failing in this PR than there were before. You can look at the comparison between [master](https://travis-ci.org/hermanschaaf/mafan/builds/73310084) (which also failed, but with only 2 errors, a year ago) and [this branch](https://travis-ci.org/hermanschaaf/mafan/builds/151130836). I'll be happy to merge this if, at least, it doesn't introduce new errors for Python 2.7 users.

**Comment by JOEWONGLVFS** [comment]
@hermanschaaf I'm really sorry. I have just joined Github and have only been working with Python for a few months... But as far as I understand it, there are many differences between Python 2.x and 3.x which are not compatible. For example, the _print_ clause has been altered into a function, and _raw_input()_ has been renamed _input()_ ... I think creating a new package just for Python 3.x would be better.

**Comment by hermanschaaf** [comment]
hi @JOEWONGLVFS, I'm not an expert on the topic of 2.7 to 3.x conversion either, but I believe it is possible to run both without issues.

For example, to use the `print` function in 2.7, you can include `from __future__ import print`. As for `raw_input`, you can do something like:

```
>>> try:
...     input = raw_input
... except NameError:
...     pass
```

I believe there are workarounds for all these issues, as many library support both Python 2.7 and 3.x. With more around half of the community still using 2.7, I think it makes sense to aim for dual support.

**Comment by hermanschaaf** [comment]
This guide seems like it would be useful:

http://python3porting.com/differences.html

**Comment by cychiang** [comment]
Hi (@hermanschaaf, @JOEWONGLVFS ):
It seems that the Travis-CI needs a new configuration file to support Python 3 in order to pass CI build check. I would like to spend some time to work on it and solve some existing issues on current build.

**Comment by hermanschaaf** [comment]
Thanks @cychiang, that would be awesome. I would be happy to review and merge any changes you make.

**Comment by hermanschaaf** [comment]
This was merged as part of https://github.com/hermanschaaf/mafan/issues/17.

**Pull request closed without merging**
